export const STACK_NAME = {
  ROOT: 'Root',
  LOGIN: 'Login',
  SIGNUP: 'SignUp',
  RESET_PASSWORD: 'ResetPassword',
  EXPLORE: 'Explore',
  FEED: 'Post',
  FEED_CREATE: 'PostCreate',
  FEED_UPDATE: 'PostUpdate',
  FEED_DETAIL: 'PostDetail',
  MAP: 'Map',
  DM: 'DM',
  PROFILE: 'Profile',
  PROFILE_UPDATE: 'ProfileUpdate',
} as const;
