export const STACK_NAME = {
  ROOT: 'Root',
  LOGIN: 'Login',
  SIGNUP: 'SignUp',
  RESET_PASSWORD: 'ResetPassword',
  EXPLORE: 'Explore',
  POST: 'Post',
  POST_CREATE: 'PostCreate',
  POST_UPDATE: 'PostUpdate',
  POST_DETAIL: 'PostDetail',
  MAP: 'Map',
  DM: 'DM',
  PROFILE: 'Profile',
  PROFILE_UPDATE: 'ProfileUpdate',
  SETTING: 'Setting',
} as const;
